### ISSUE TITLE
1-year badge

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#10]
We need to get the 1-year badge on the website.

**Comment by An0n3m0us** [comment]
This one, correct?:
https://www.khanacademy.org/computer-programming/entry/4715418887274496

**Comment by KALoneNinja** [comment]
I copied it to the TEE team account. It is safer using that one. Plus that one doesn't have a transparent background.

You know what I found out about the transparent background going with the image? You have to put the "i" instead of the title in the url.

**Comment by An0n3m0us** [comment]
Ah okay, interesting. I think maybe the top right corner might work. Or do the events show up there?

**Comment by KALoneNinja** [comment]
Yeah, the events show up there. I think the badge was meant for members.

**Comment by An0n3m0us** [comment]
Yeah, I think so too. I'll close this issue then.
