### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#11]
When you click outside of the sidebar it should exit.

Also, button responses to a hover/click might be nice.

**Comment by An0n3m0us** [comment]
Clicking outside of the sidebar should close it, I agree.
Both buttons have hover animations already.

**Comment by An0n3m0us** [comment]
I added closing of the sidebar when clicking outside. I accidentally pushed it without creating a PR xD:
https://github.com/An0n3m0us/KhanAcademy-TEE/commit/184e8dee4a6ce9cf4666b13e2eb870e615941d66

I'll add it to KA after you've checked it.

**Comment by KALoneNinja** [comment]
Are we both talking about the page changing buttons? (not the open/close sidebar ones)

It is okay, but there are a few buggy spots, how about something like:
`<script>
        $("body").on("click", function(evt){
            var clas = evt.target.className;
            console.log(clas);
            if( clas.includes("sidenav") || clas.includes("sidebar-image") || clas.includes("openbtn") ){
                console.log("Open")
            } else{
                console.log("Close")
            }
        })
    </script>`

Note that the sidebar-image might want to close it instead of open it :P

**Comment by An0n3m0us** [comment]
Oh, the page buttons? Who cares xD
The tab closes rather quickly when one clicks on them anyway. I'll probably make some hover CSS though.

As for the code above, it didn't work.

**Comment by KALoneNinja** [comment]
Yeah, I only made it log to the console. :P

**Comment by An0n3m0us** [comment]
The sidebar remains open even if one of the page buttons are clicked.
Is this how you intended it to be?

**Comment by KALoneNinja** [comment]
No.

**Comment by An0n3m0us** [comment]
Nevermind; I fixed it.

**Comment by KALoneNinja** [comment]
`class` is a keyword in javascript. It isn't taught on KA. It is like saying`var`, so I couldn't use it.

Here is the working code:
```
<script>
    	function closeNav() {
    		document.getElementById("sidenav").style.width = "0";
    	}
        $("body").on("click", function(evt){
            var clas = evt.target.className;
            console.log(clas);
            if( !(clas.includes("sidenav") || clas.includes("openbtn")) ){
                closeNav();
                
            }
        })
        $('.openbtn').click(function(){
			  document.getElementById("sidenav").style.width = "100px";
		  });
    </script>
```

**Comment by KALoneNinja** [comment]
Although the console.log could be taken out.

**Comment by An0n3m0us** [comment]
I got it working like this:

```
function closeNav() {
  document.getElementById("sidenav").style.width = "0";
}

$("body").on("click", function(evt){
	var clas = evt.target.className;
	if( clas.includes("sidenav") || clas.includes("openbtn") ){
	    document.getElementById("sidenav").style.width = "100px";
	} else {
	    closeNav()
	}
})
```

**Comment by KALoneNinja** [comment]
Cool!
