### ISSUE TITLE
Leaderboard Generation

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#12]
We should make a button to auto-generate the weekly leaderboard to make Christelle and MBONKA's work easier.  I was thinking that we could make it only appear when you put: ?admin=true in the url

**Comment by An0n3m0us** [comment]
That's possible. I'll see if I can work on this later.

**Comment by An0n3m0us** [comment]
Closed by JSFiddle project.
