### ISSUE TITLE
Verification Thread

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#13]
I was thinking we could append to the member object using the thread created by their PI in the verification thread.

**Comment by An0n3m0us** [comment]
Append what to the member object?

**Comment by KALoneNinja** [comment]
Append members from the PI verification comments.

**Comment by An0n3m0us** [comment]
This is possible. I was thinking of cleaning the current code first because it contains many duplicates and odd ways of doing things.
