### ISSUE TITLE
Weekly Leaderboard Searching

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#14]
The searching by name and id are overwritten by the constant sorting by evaluations that was added previously.

**Comment by An0n3m0us** [comment]
Hmm, I'm sure I set it to load all of the evaluations into the table first before displaying it.

**Comment by KALoneNinja** [comment]
Fixed! With: #28

**Comment by An0n3m0us** [comment]
You should close this issue after the PR has been merged : )

**Comment by KALoneNinja** [comment]
lol, true
