### ISSUE TITLE
Title&Role sort Fix

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#16]
The title&role sort doesn't work.

**Comment by An0n3m0us** [comment]
I'm planning to work on this too.

**Comment by An0n3m0us** [comment]
Hmm, how would this work? We cannot sort alphabetically nor numerically.
I'm thinking of something like assigning numbers to the roles and somehow sorting that way.

**Comment by KALoneNinja** [comment]
I think what I did when it was working was throw members into arrays for each title and each role like 
`[role][title].push(member);`

Then we can just have an array of each title and role:
`["Founder", "Peer Instructor", "Evaluator"]`
`["Highest_Rank", "Second_Highest_Rank", ... "Evaluator"]`

Then literally all you have to do is move the members into there, then combine those arrays using a loop like:
```var members = [];
for(var i = 0; i < roles.length; i ++){
    for(var i2 = 0; i2 < titles.length; i2++){
        members.concat(members2[roles[i]][titles[i2]]);
    }
}```
