### ISSUE TITLE
Code is susceptible to running duplicate kaids

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#24]
We had two kaids in the verification thread (oops). This made the kaids increase, but the done not which lead to it being stuck at 90%. It would be nice to have a safety measure for this.

**Comment by An0n3m0us** [comment]
Agreed. This might work:
https://stackoverflow.com/a/9229932

**Comment by An0n3m0us** [comment]
Fixed by fa0e1c2
