### ISSUE TITLE
Feedback Joining Responsibility

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#7]
We need to add that you must have feedback in your evaluations.

**Comment by An0n3m0us** [comment]
As a rule for joining TEE?
Also, will this apply only to projects that have failed to pass, or all projects?

**Comment by KALoneNinja** [comment]
It is already a rule, if you don't give feedback you won't be on the leaderboard. It just isn't mentioned in the responsibilities section.

Well failed projects should have some encouraging feedback, so yeah all of the evaluations should have feedback.

**Comment by An0n3m0us** [comment]
Closed by #19
