### ISSUE TITLE
Footer section links

### ISSUE THREAD

**Issue by KALoneNinja** [An0n3m0us/KhanAcademy-TEE#8]
We should add links to each page in the footer

**Comment by An0n3m0us** [comment]
Which pages specifically? The pages within the website?

**Comment by KALoneNinja** [comment]
Yeah, all of the pages within the website:

Joining
Members
Leaderboard (weekly)
leaaderboard (total)
resources
home
archives
weekly winners
hall of fame

**Comment by An0n3m0us** [comment]
Closed by #19
